#!/usr/bin/env bash
# Generated by scripts/prepare-run.py
set -e
cd $RUN_DIR/alice-runtime
export TMPDIR=$RUN_DIR/tmp/alice
$PYTHON $ROOT/scripts/alice-launcher.py --harness claude-code --hub-url http://127.0.0.1:8420 --token-file $HUB_REPO/.robomate/token --sessions $RUN_DIR/alice-sessions.jsonl --resume-delay-s 5 --resume-max-delay-s 1800 --resume-total-s 43200 --resume-series-reset-s 300 --prompt $RUN_DIR/alice.prompt.md -- claude --permission-mode auto --strict-mcp-config --mcp-config $RUN_DIR/configs/alice.mcp.json --add-dir $RUN_DIR
