#!/usr/bin/env bash
# Generated by scripts/prepare-run.py
set -e
cd $RUN_DIR/alice-runtime
export TMPDIR=$RUN_DIR/tmp/alice
claude --permission-mode auto --strict-mcp-config --mcp-config $RUN_DIR/configs/alice.mcp.json --add-dir $RUN_DIR -p 'Read $RUN_DIR/alice.prompt.md and follow the instructions in it'
