#!/usr/bin/env bash
# Generated by scripts/prepare-run.py
set -e
cd $RUN_DIR/charlie
CODEX_HOME=$RUN_DIR/configs/codex codex exec -C . --add-dir $RUN_DIR/charlie/.git --approve-for-me - < $RUN_DIR/charlie.prompt.md
